"""initial_database_creation_clean_final

Revision ID: 9d29a0b9c1af
Revises: 
Create Date: 2025-11-28 23:01:23.811934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d29a0b9c1af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    op.create_table('categorymapping',
    sa.Column('original_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorymapping_original_category'), 'categorymapping', ['original_category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tool',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('official_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pricing_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('submitter_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('use_cases', sa.JSON(), nullable=True),
    sa.Column('key_differentiators', sa.JSON(), nullable=True),
    sa.Column('pricing_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('pros', sa.JSON(), nullable=True),
    sa.Column('cons', sa.JSON(), nullable=True),
    sa.Column('faqs', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supported_platforms', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_category'), 'tool', ['category'], unique=False)
    op.create_index(op.f('ix_tool_category_name'), 'tool', ['category_name'], unique=False)
    op.create_index(op.f('ix_tool_name'), 'tool', ['name'], unique=False)
    op.create_index(op.f('ix_tool_review_status'), 'tool', ['review_status'], unique=False)
    op.create_index(op.f('ix_tool_slug'), 'tool', ['slug'], unique=True)
    op.create_index(op.f('ix_tool_submitter_email'), 'tool', ['submitter_email'], unique=False)
    op.create_index(op.f('ix_tool_submitter_id'), 'tool', ['submitter_id'], unique=False)
    op.create_table('workflowtemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('IMAGE_GENERATOR', 'TEXT_GENERATOR', 'VIDEO_EDITOR', 'AUDIO_PROCESSOR', 'MARKETING', 'PRODUCTIVITY', 'DEVELOPMENT', 'OTHER', name='workflowtemplatecategory'), nullable=False),
    sa.Column('flow_chart_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflowtemplate_category'), 'workflowtemplate', ['category'], unique=False)
    op.create_index(op.f('ix_workflowtemplate_status'), 'workflowtemplate', ['status'], unique=False)
    op.create_index(op.f('ix_workflowtemplate_title'), 'workflowtemplate', ['title'], unique=False)
    op.create_table('workflownode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workflowtemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflownode_order'), 'workflownode', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflownode_order'), table_name='workflownode')
    op.drop_table('workflownode')
    op.drop_index(op.f('ix_workflowtemplate_title'), table_name='workflowtemplate')
    op.drop_index(op.f('ix_workflowtemplate_status'), table_name='workflowtemplate')
    op.drop_index(op.f('ix_workflowtemplate_category'), table_name='workflowtemplate')
    op.drop_table('workflowtemplate')
    op.drop_index(op.f('ix_tool_submitter_id'), table_name='tool')
    op.drop_index(op.f('ix_tool_submitter_email'), table_name='tool')
    op.drop_index(op.f('ix_tool_slug'), table_name='tool')
    op.drop_index(op.f('ix_tool_review_status'), table_name='tool')
    op.drop_index(op.f('ix_tool_name'), table_name='tool')
    op.drop_index(op.f('ix_tool_category_name'), table_name='tool')
    op.drop_index(op.f('ix_tool_category'), table_name='tool')
    op.drop_table('tool')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categorymapping_original_category'), table_name='categorymapping')
    op.drop_table('categorymapping')
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
